### PR TITLE
bump: Akka 2.8.1

### PR DESCRIPTION
**Pull request by johanandren**

### CODE REVIEW

**Comment by octonato** [comment]
some Scala 3 compilation error though

**Comment by johanandren** [comment]
We need to bump Scala 3.2 here as well I think

**Comment by johanandren** [comment]
Surprising results when building locally, `+Test/compile` works for all Scala versions, `++3.2.2; Test/compile` does not.

**Comment by patriknw** [comment]
> +Test/compile works for all Scala versions, ++3.2.2; Test/compile

That is because we have mixed cross scala versions in the projects here. Sbt can't handle that for `++3`, but `+Test/compile` works.

**Comment by johanandren** [comment]
Ah, we talked about that before, seems I am unable to store that in brain.

**Pull request merged**
