### PR TITLE
docs: add repository info

### PR DESCRIPTION
**Pull request by aludwiko**

### CODE REVIEW

**Review by franciscolopezsancho — APPROVED** [review]
LGTM

**Review by efgpinto — APPROVED** [review]
LGTM

**Comment by franciscolopezsancho** [comment]
You asked this question already 
here you have `@@repository [Maven,sbt,Gradle] {`

in some other [PRs](https://github.com/akka/akka-persistence-jdbc/pull/756/files)
`@@repository [sbt,Maven,Gradle] {`

I think would be fine if you want to decide which is the right one and use it all along.

**Comment by aludwiko** [comment]
@franciscolopezsancho yes, for now I'm just keeping the same order as the current one.

**Pull request merged**
